# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180221_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='cantidad',
        ),
    ]
