# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_noticia_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='address',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefono',
        ),
    ]
