# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180222_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
