# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180222_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='name',
        ),
    ]
