# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='datos',
            field=models.CharField(max_length=200),
        ),
    ]
