# Generated by Django 2.0.1 on 2018-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180411_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='datos',
            field=models.CharField(max_length=500),
        ),
    ]
